#ifndef _PHOTOBOOTH_PSU_H
#define _PHOTOBOOTH_PSU_H

#define PIN_RELAIS1 C,6
#define PIN_RELAIS2 D,7
#define PIN_RELAIS3 E,6
#define PIN_RELAIS4 B,4
#define PIN_PWR_BTN B,5
#define PIN_UART_TX D,3
#define PIN_UART_RX D,2
#define PIN_PSON    D,4
#define PIN_PWR_LED B,6
#define PIN_RASPBERRY_BOOT_COMPLETE F,7
#define PIN_RASPBERRY_STATE B,3
#define PIN_RASPBERRY_SHUTDOWN B,1

#endif //_PHOTOBOOTH_PSU_H
